### ISSUE TITLE
Update to use ECR?

### ISSUE THREAD

**Issue by chiefy** [Capgemini/terraform-amazon-ecs#9]
What about using [ECR](https://www.terraform.io/docs/providers/aws/r/ecr_repository.html)? Seems like less hassle than setting it up to run in ECS?

**Comment by tayzlor** [comment]
looks reasonable, when we wrote the code that wasn't available through terraform. PRs are welcome :space_invader:  only potential hiccup I see is its only available in us-east region.

**Comment by chiefy** [comment]
Ugh, yeah, totally forgot it hasn't been rolled out to other regions.

**Comment by recurrence** [comment]
Rolled out all over now :)
